nines_user:
  resource: '@NinesUserBundle/Resources/config/routes.yaml'

nines_editor:
  type: annotation
  prefix: /editor
  resource: '@NinesEditorBundle/Controller'

nines_media:
  type: annotation
  prefix: /media
  resource: '@NinesMediaBundle/Controller'

nines_blog:
  type: annotation
  prefix: /blog
  resource: '@NinesBlogBundle/Controller'
