title: AMP
description: Documentation for the AMP project
theme: just-the-docs
url: https://amp.dhil.lib.sfu.ca/docs
baseurl: /docs
heading_anchors: true
callouts:
  warning:
    title: Warning
    color: yellow
    opacity: 0.2
  important:
    title: Important
    color: blue
    opacity: 0.2
  note:
    title: Note
    color: purple
    opacity: 0.2
aux_links:
  "AMP Source Code on Github":
    - https://github.com/sfu-dhil/amplify
nav_external_links: []
gh_edit_link: false
color_scheme: amp
exclude:
- tbls_templates
sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607